import tictactie from "../image/projectsicon/tictactoe.png";

const projectsInfo = [
  {
    name: "Seamless Integration: RosaeNLG Narratives Meet PowerBI",
    link: "https://github.com/2015pushkar/Seamless-Integration",
    desc: "Integration project",
    summary: "Integration of RosaeNLG natural language narratives with PowerBI using TypeScript",
    summary2: "TypeScript, PowerBI, RosaeNLG",
    imgSrc: tictactie,
    categories:"Data Analysis",
    type:"company",
  },
  {
    name: "Sales Dashboard using React-charts-JS library",
    link: "https://github.com/2015pushkar/Sales-Dashboard",
    desc: "Interactive sales dashboard",
    summary: "Interactive sales dashboards with React-charts-JS-2 library",
    summary2: "React.JS, React-charts-JS-2",
    imgSrc: tictactie,
    categories:"Data Analysis",
    type:"company",
  },
  {
    name: "Sales Analytics Dashboard using GoodData BI and React.JS",
    link: "https://github.com/2015pushkar/Sales-Analytics-Dashboard",
    desc: "Sales analytics dashboard",
    summary: "Sales analytics dashboards using GoodData BI and React.JS",
    summary2: "React.JS, GoodData BI",
    imgSrc: tictactie,
    categories:"Data Analysis",
    type:"client",
  },
  {
    name: "krtrimaIQ Cognitive Solution Website",
    link: "https://github.com/2015pushkar/Digital-Assistants-Chatbot",
    desc: "Digital assistants chatbot",
    summary: "Developed digital assistants using Next.js and Rasa",
    summary2: "Next.JS",
    imgSrc: tictactie,
    categories:"Web Development",
    type:"company",
  },
  {
    name: "Digital Assistants Chatbot using Next.JS and Rasa",
    link: "https://github.com/2015pushkar/Digital-Assistants-Chatbot",
    desc: "Digital assistants chatbot",
    summary: "Developed digital assistants using Next.js and Rasa",
    summary2: "Next.JS, Rasa",
    imgSrc: tictactie,
    categories:"Web Development",
    type:"company",
  },
  {
    name: "PnL Website for a Publication House",
    link: "https://github.com/2015pushkar/Digital-Assistants-Chatbot",
    desc: "Digital assistants chatbot",
    summary: "Developed digital assistants using Next.js and Rasa",
    summary2: "React.JS",
    imgSrc: tictactie,
    categories:"Web Development",
    type:"client",
  },
  {
    name: "Big Data - Type 2 SCD in Azure Data Factory",
    link: "https://github.com/2015pushkar/Big-Data-SCD",
    desc: "Type 2 SCD implementation",
    summary: "Implemented Type 2 Slowly Changing Dimensions (SCD) in Azure Data Factory",
    summary2: "Azure SQL Database, Azure Data Factory, Azure Databricks, Azure Synapse Analytics, Python",
    imgSrc: tictactie,
    categories:"Data Engineering",
    type:"company",
  },
  {
    name: "Loan Eligibility Prediction (Machine Learning)",
    link: "https://github.com/2015pushkar/Loan-Eligibility-Prediction",
    desc: "Loan eligibility prediction",
    summary: "Classification model to predict loan eligibility based on customer application data",
    summary2: "Python, Classification",
    imgSrc: tictactie,
    categories:"Machine Learning",
    type:"company",
  },
  {
    name: "Book Recommendation System (Collaborative Filtering)",
    link: "https://github.com/2015pushkar/Book-Recommendation-System",
    desc: "Book recommendation system",
    summary: "Recommendation system suggesting items to users based on past interactions",
    summary2: "Python, Collaborative Filtering",
    imgSrc: tictactie,
    categories:"Machine Learning",
    type:"company",
  },
  {
    name: "Diabetes Prediction (Support Vector Machines)",
    link: "https://github.com/2015pushkar/Diabetes-Prediction-SVM",
    desc: "Diabetes prediction",
    summary: "Analyzed diabetes dataset attributes and applied SVM model for accurate classification",
    summary2: "Python, Support Vector Machines",
    imgSrc: tictactie,
    categories:"Machine Learning",
    type:"company",
  },
  {
    name: "COVID-19 Data Analysis",
    link: "https://github.com/2015pushkar/COVID-19-Data-Analysis",
    desc: "COVID-19 data analysis",
    summary: "Performed exploratory data analysis on COVID-19 datasets",
    summary2: "Python",
    imgSrc: tictactie,
    categories:"Data Analysis",
    type:"company",
  },
  {
    name: "Tic-Tac-Toe Game (C Language)",
    link: "https://github.com/2015pushkar/Tic-Tac-Toe-Game",
    desc: "Tic-Tac-Toe game",
    summary: "Developed a Tic-Tac-Toe game following best software development practices",
    summary2: "C Language",
    imgSrc: tictactie,
    categories:"Web development",
    type:"company",
  },
  {
    name: "Relay Assisted Pliable Index Coding",
    link: "https://github.com/2015pushkar/Relay-Assisted-PIC",
    desc: "Pliable Index Coding project",
    summary: "Implemented network coding with relay assistance to optimize communication system performance",
    summary2: "Python, Matlab, Computer Networks",
    imgSrc: tictactie,
    categories:"Networking",
    type:"company",
  },
];

export default projectsInfo;
